services:
  - type: web
    name: grodno-news-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      wget -O Montserrat-Black.ttf https://github.com/google/fonts/raw/main/ofl/montserrat/Montserrat-Black.ttf || true
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
    buildFilter:
      paths:
        - bot.py
        - requirements.txt
